### ISSUE TITLE
organization and frustration

### ISSUE THREAD

**Issue by insyri** [nwanne56/dbot#2]
have an `src` folder for all the bare written files and a separate `dist` folder among all the files, meaning not what you have here having 2 different sub dist folders, just have whole folder dedicated for the code itself. example:

![image](https://user-images.githubusercontent.com/60794909/124839440-cd54cb80-df56-11eb-899b-efa12264f971.png)

this bull:
config/dist/
dist/
modules/basic/dist/

naw thats not how it works

dist/modules/basic
dist/config

yes

**Comment by nwanne56** [comment]
removed dist folders
